# Generated by Django 4.0.5 on 2022-06-27 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decription_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='sensor_data',
            new_name='humi',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='sensor_name',
            new_name='rain',
        ),
        migrations.AddField(
            model_name='mydata',
            name='rays',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mydata',
            name='soilm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mydata',
            name='temp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
